//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.19 at 03:32:02 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fort.org/shemas/base")
package org.fort.shemas.base;
